main: com.cavetale.customizablebonemeal.CustomizableBonemealPlugin
name: CustomizableBonemeal
version: 0.1
api-version: 1.13
description: CustomizableBonemeal Plugin
author: StarTux
website: https://cavetale.com
depend: []
softdepend: []
permissions:
  cbm.cbm:
    description: Use custom bonemeal
    default: op